export enum RoleProfileInternal {
  FOPS_COMPANY_SUPERVISORDELINEA = 11,
  FOPS_COMPANY_SUPERVISORDECALIDAD = 12,
  FOPS_COMPANY_OPERADORPISO = 13,
  FOPS_COMPANY_AUDITORDECALIDAD = 14,
  FOPS_COMPANY_COORDINADORDELINEA = 15
}